[project]
name = "dragon-torch"
version = "0.1.0"
description = "PyTorch Deep Learning Research framework"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax",
    "torch",
    "torchvision",
]

[project.optional-dependencies]

cpu=[
    "jax>=0.11.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

cuda12 = [
    "jax[cuda12]>=0.11.2",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

cuda13 = [
    "jax[cuda13]>=0.11.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cuda12" },
    { extra = "cuda13" },
  ],
]

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-cuda12"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "torch-cuda13"
url = "https://download.pytorch.org/whl/cu130"
explicit = true


[tool.uv.sources]
torch = [
  { index = "torch-cpu", extra = "cpu" },
  { index = "torch-cuda12", extra = "cuda12" },
  { index = "torch-cuda13", extra = "cuda13" },
]
torchvision = [
  { index = "torch-cpu", extra = "cpu" },
  { index = "torch-cuda12", marker = "sys_platform == 'linux'", extra = "cuda12" },
  { index = "torch-cuda13", marker = "sys_platform == 'linux'", extra = "cuda13" },
]